spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cookbook_db
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
